// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserAPIKey = `-- name: DeleteUserAPIKey :exec
DELETE FROM user_api_keys
WHERE user_id = $1 AND provider = $2
`

type DeleteUserAPIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteUserAPIKey(ctx context.Context, arg DeleteUserAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserAPIKey, arg.UserID, arg.Provider)
	return err
}

const getUserAPIKey = `-- name: GetUserAPIKey :one
SELECT encrypted_key
FROM user_api_keys
WHERE user_id = $1 AND provider = $2
`

type GetUserAPIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetUserAPIKey(ctx context.Context, arg GetUserAPIKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserAPIKey, arg.UserID, arg.Provider)
	var encrypted_key string
	err := row.Scan(&encrypted_key)
	return encrypted_key, err
}

const listUserAPIKeyProviders = `-- name: ListUserAPIKeyProviders :many
SELECT provider
FROM user_api_keys
WHERE user_id = $1
ORDER BY provider
`

func (q *Queries) ListUserAPIKeyProviders(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserAPIKeyProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAPIKey = `-- name: UpsertUserAPIKey :exec
INSERT INTO user_api_keys (user_id, provider, encrypted_key)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, provider)
DO UPDATE SET encrypted_key = EXCLUDED.encrypted_key, updated_at = NOW()
`

type UpsertUserAPIKeyParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	EncryptedKey string    `json:"encrypted_key"`
}

func (q *Queries) UpsertUserAPIKey(ctx context.Context, arg UpsertUserAPIKeyParams) error {
	_, err := q.db.Exec(ctx, upsertUserAPIKey, arg.UserID, arg.Provider, arg.EncryptedKey)
	return err
}
