// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    user_id, job_id, application_status, applied_at, notes, follow_up_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, job_id, application_status, applied_at, last_status_changed_at, follow_up_at, notes, created_at, updated_at
`

type CreateApplicationParams struct {
	UserID            uuid.UUID  `json:"user_id"`
	JobID             uuid.UUID  `json:"job_id"`
	ApplicationStatus string     `json:"application_status"`
	AppliedAt         *time.Time `json:"applied_at"`
	Notes             *string    `json:"notes"`
	FollowUpAt        *time.Time `json:"follow_up_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.JobID,
		arg.ApplicationStatus,
		arg.AppliedAt,
		arg.Notes,
		arg.FollowUpAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.LastStatusChangedAt,
		&i.FollowUpAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1 AND user_id = $2
`

type DeleteApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.UserID)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT
    id,
    user_id,
    job_id,
    application_status,
    applied_at,
    notes,
    follow_up_at,
    created_at,
    updated_at
FROM applications
WHERE id = $1 AND user_id = $2
`

type GetApplicationByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetApplicationByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	JobID             uuid.UUID          `json:"job_id"`
	ApplicationStatus string             `json:"application_status"`
	AppliedAt         *time.Time         `json:"applied_at"`
	Notes             *string            `json:"notes"`
	FollowUpAt        *time.Time         `json:"follow_up_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (GetApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, arg.ID, arg.UserID)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.Notes,
		&i.FollowUpAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByUserAndJob = `-- name: GetApplicationByUserAndJob :one
SELECT
    id,
    user_id,
    job_id,
    application_status,
    applied_at,
    notes,
    follow_up_at,
    created_at,
    updated_at
FROM applications
WHERE user_id = $1 AND job_id = $2
`

type GetApplicationByUserAndJobParams struct {
	UserID uuid.UUID `json:"user_id"`
	JobID  uuid.UUID `json:"job_id"`
}

type GetApplicationByUserAndJobRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	JobID             uuid.UUID          `json:"job_id"`
	ApplicationStatus string             `json:"application_status"`
	AppliedAt         *time.Time         `json:"applied_at"`
	Notes             *string            `json:"notes"`
	FollowUpAt        *time.Time         `json:"follow_up_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApplicationByUserAndJob(ctx context.Context, arg GetApplicationByUserAndJobParams) (GetApplicationByUserAndJobRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByUserAndJob, arg.UserID, arg.JobID)
	var i GetApplicationByUserAndJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.Notes,
		&i.FollowUpAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationsByUserID = `-- name: GetApplicationsByUserID :many
SELECT
    a.id,
    a.user_id,
    a.job_id,
    a.application_status,
    a.applied_at,
    a.notes,
    a.follow_up_at,
    a.created_at,
    a.updated_at,
    j.title AS job_title,
    j.company_name,
    j.job_location,
    j.source_url,
    j.is_remote AS job_is_remote,
    j.logo_url AS job_logo_url
FROM applications AS a
INNER JOIN jobs AS j ON a.job_id = j.id
WHERE a.user_id = $1
ORDER BY a.updated_at DESC
`

type GetApplicationsByUserIDRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	JobID             uuid.UUID          `json:"job_id"`
	ApplicationStatus string             `json:"application_status"`
	AppliedAt         *time.Time         `json:"applied_at"`
	Notes             *string            `json:"notes"`
	FollowUpAt        *time.Time         `json:"follow_up_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	JobTitle          string             `json:"job_title"`
	CompanyName       string             `json:"company_name"`
	JobLocation       *string            `json:"job_location"`
	SourceUrl         string             `json:"source_url"`
	JobIsRemote       *bool              `json:"job_is_remote"`
	JobLogoUrl        *string            `json:"job_logo_url"`
}

func (q *Queries) GetApplicationsByUserID(ctx context.Context, userID uuid.UUID) ([]GetApplicationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationsByUserIDRow
	for rows.Next() {
		var i GetApplicationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.ApplicationStatus,
			&i.AppliedAt,
			&i.Notes,
			&i.FollowUpAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.CompanyName,
			&i.JobLocation,
			&i.SourceUrl,
			&i.JobIsRemote,
			&i.JobLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationFollowUp = `-- name: UpdateApplicationFollowUp :one
UPDATE applications
SET
    follow_up_at = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, job_id, application_status, applied_at, last_status_changed_at, follow_up_at, notes, created_at, updated_at
`

type UpdateApplicationFollowUpParams struct {
	ID         uuid.UUID  `json:"id"`
	FollowUpAt *time.Time `json:"follow_up_at"`
	UserID     uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateApplicationFollowUp(ctx context.Context, arg UpdateApplicationFollowUpParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationFollowUp, arg.ID, arg.FollowUpAt, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.LastStatusChangedAt,
		&i.FollowUpAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationNotes = `-- name: UpdateApplicationNotes :one
UPDATE applications
SET
    notes = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, job_id, application_status, applied_at, last_status_changed_at, follow_up_at, notes, created_at, updated_at
`

type UpdateApplicationNotesParams struct {
	ID     uuid.UUID `json:"id"`
	Notes  *string   `json:"notes"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationNotes, arg.ID, arg.Notes, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.LastStatusChangedAt,
		&i.FollowUpAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET
    application_status = $2,
    last_status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, job_id, application_status, applied_at, last_status_changed_at, follow_up_at, notes, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID                uuid.UUID `json:"id"`
	ApplicationStatus string    `json:"application_status"`
	UserID            uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus, arg.ID, arg.ApplicationStatus, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.ApplicationStatus,
		&i.AppliedAt,
		&i.LastStatusChangedAt,
		&i.FollowUpAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
