// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package database

import (
	"context"
	"database/sql"
)

const updateServiceHealth = `-- name: UpdateServiceHealth :one
INSERT INTO service_health (
    service_name, last_run_at, last_success_at, status, last_error, job_count_last_run
) VALUES (
    $1, NOW(), $2, $3, $4, $5
)
ON CONFLICT (service_name) DO UPDATE SET
   last_run_at = EXCLUDED.last_run_at,
   last_success_at = COALESCE(
        EXCLUDED.last_success_at,       -- new value (maybe be null)
        service_health.last_success_at  -- existing value (fallback)
    ),
   status = EXCLUDED.status,
   last_error = EXCLUDED.last_error,
   job_count_last_run = EXCLUDED.job_count_last_run,
   updated_at = NOW()
RETURNING id, service_name, last_run_at, last_success_at, status, last_error, job_count_last_run, updated_at
`

type UpdateServiceHealthParams struct {
	ServiceName     string         `json:"service_name"`
	LastSuccessAt   sql.NullTime   `json:"last_success_at"`
	Status          string         `json:"status"`
	LastError       sql.NullString `json:"last_error"`
	JobCountLastRun sql.NullInt32  `json:"job_count_last_run"`
}

func (q *Queries) UpdateServiceHealth(ctx context.Context, arg UpdateServiceHealthParams) (ServiceHealth, error) {
	row := q.db.QueryRowContext(ctx, updateServiceHealth,
		arg.ServiceName,
		arg.LastSuccessAt,
		arg.Status,
		arg.LastError,
		arg.JobCountLastRun,
	)
	var i ServiceHealth
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.LastRunAt,
		&i.LastSuccessAt,
		&i.Status,
		&i.LastError,
		&i.JobCountLastRun,
		&i.UpdatedAt,
	)
	return i, err
}
