// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    external_id, source, title, company, description, url,
    salary_min, salary_max, currency, location, is_remote, skills, logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (external_id, source) DO NOTHING
RETURNING id, external_id, source, title, company, description, url, salary_min, salary_max, currency, location, is_remote, status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url
`

type CreateJobParams struct {
	ExternalID  string         `json:"external_id"`
	Source      string         `json:"source"`
	Title       string         `json:"title"`
	Company     string         `json:"company"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	SalaryMin   sql.NullInt32  `json:"salary_min"`
	SalaryMax   sql.NullInt32  `json:"salary_max"`
	Currency    sql.NullString `json:"currency"`
	Location    sql.NullString `json:"location"`
	IsRemote    sql.NullBool   `json:"is_remote"`
	Skills      []string       `json:"skills"`
	LogoUrl     sql.NullString `json:"logo_url"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ExternalID,
		arg.Source,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.Url,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.Currency,
		arg.Location,
		arg.IsRemote,
		pq.Array(arg.Skills),
		arg.LogoUrl,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.Url,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.Currency,
		&i.Location,
		&i.IsRemote,
		&i.Status,
		&i.EmploymentType,
		&i.ExperienceLevel,
		pq.Array(&i.Skills),
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}
