// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    external_id, job_source, title, company_name, description, source_url,
    salary_min, salary_max, currency, job_location, is_remote, skills, logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (external_id, job_source) DO NOTHING
RETURNING id, external_id, job_source, title, company_name, description, source_url, salary_min, salary_max, currency, job_location, is_remote, job_status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url
`

type CreateJobParams struct {
	ExternalID  string   `json:"external_id"`
	JobSource   string   `json:"job_source"`
	Title       string   `json:"title"`
	CompanyName string   `json:"company_name"`
	Description *string  `json:"description"`
	SourceUrl   string   `json:"source_url"`
	SalaryMin   *int32   `json:"salary_min"`
	SalaryMax   *int32   `json:"salary_max"`
	Currency    *string  `json:"currency"`
	JobLocation *string  `json:"job_location"`
	IsRemote    *bool    `json:"is_remote"`
	Skills      []string `json:"skills"`
	LogoUrl     *string  `json:"logo_url"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ExternalID,
		arg.JobSource,
		arg.Title,
		arg.CompanyName,
		arg.Description,
		arg.SourceUrl,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.Currency,
		arg.JobLocation,
		arg.IsRemote,
		arg.Skills,
		arg.LogoUrl,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.JobSource,
		&i.Title,
		&i.CompanyName,
		&i.Description,
		&i.SourceUrl,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.Currency,
		&i.JobLocation,
		&i.IsRemote,
		&i.JobStatus,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Skills,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}

const getAllJobIDs = `-- name: GetAllJobIDs :many
SELECT id FROM jobs
`

func (q *Queries) GetAllJobIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllJobIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT
    j.id,
    j.external_id,
    j.job_source,
    j.title,
    j.company_name,
    j.description,
    j.source_url,
    j.salary_min,
    j.salary_max,
    j.currency,
    j.job_location,
    j.is_remote,
    j.skills,
    j.logo_url,
    j.created_at,
    j.updated_at,
    m.match_score,
    m.title_score,
    m.skill_score,
    m.experience_score,
    m.matched_skills,
    m.missing_skills,
    m.ai_summary,
    m.is_enriched,
    m.created_at AS match_created_at,
    m.updated_at AS match_updated_at,
    (s.id IS NOT NULL)::BOOLEAN AS is_saved,
    (a.id IS NOT NULL)::BOOLEAN AS is_applied,
    (m.id IS NOT NULL)::BOOLEAN AS is_matched
FROM jobs AS j
LEFT JOIN saved_jobs AS s ON j.id = s.job_id AND s.user_id = $1
LEFT JOIN applications AS a ON j.id = a.job_id AND a.user_id = $1
LEFT JOIN user_job_matches AS m ON j.id = m.job_id AND m.user_id = $1
WHERE j.id = $2
`

type GetJobByIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetJobByIDRow struct {
	ID              uuid.UUID     `json:"id"`
	ExternalID      string        `json:"external_id"`
	JobSource       string        `json:"job_source"`
	Title           string        `json:"title"`
	CompanyName     string        `json:"company_name"`
	Description     *string       `json:"description"`
	SourceUrl       string        `json:"source_url"`
	SalaryMin       *int32        `json:"salary_min"`
	SalaryMax       *int32        `json:"salary_max"`
	Currency        *string       `json:"currency"`
	JobLocation     *string       `json:"job_location"`
	IsRemote        *bool         `json:"is_remote"`
	Skills          []string      `json:"skills"`
	LogoUrl         *string       `json:"logo_url"`
	CreatedAt       *time.Time    `json:"created_at"`
	UpdatedAt       *time.Time    `json:"updated_at"`
	MatchScore      *int32        `json:"match_score"`
	TitleScore      pgtype.Float8 `json:"title_score"`
	SkillScore      pgtype.Float8 `json:"skill_score"`
	ExperienceScore pgtype.Float8 `json:"experience_score"`
	MatchedSkills   []string      `json:"matched_skills"`
	MissingSkills   []string      `json:"missing_skills"`
	AiSummary       *string       `json:"ai_summary"`
	IsEnriched      *bool         `json:"is_enriched"`
	MatchCreatedAt  *time.Time    `json:"match_created_at"`
	MatchUpdatedAt  *time.Time    `json:"match_updated_at"`
	IsSaved         bool          `json:"is_saved"`
	IsApplied       bool          `json:"is_applied"`
	IsMatched       bool          `json:"is_matched"`
}

func (q *Queries) GetJobByID(ctx context.Context, arg GetJobByIDParams) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, arg.UserID, arg.ID)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.JobSource,
		&i.Title,
		&i.CompanyName,
		&i.Description,
		&i.SourceUrl,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.Currency,
		&i.JobLocation,
		&i.IsRemote,
		&i.Skills,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchScore,
		&i.TitleScore,
		&i.SkillScore,
		&i.ExperienceScore,
		&i.MatchedSkills,
		&i.MissingSkills,
		&i.AiSummary,
		&i.IsEnriched,
		&i.MatchCreatedAt,
		&i.MatchUpdatedAt,
		&i.IsSaved,
		&i.IsApplied,
		&i.IsMatched,
	)
	return i, err
}

const getJobStats = `-- name: GetJobStats :one
SELECT
    COUNT(*) AS total_jobs,
    COUNT(*) FILTER (
        WHERE created_at >= DATE_TRUNC('day', NOW())
    ) AS new_jobs_today,
    MAX(created_at) AS latest_scrape_at
FROM jobs
`

type GetJobStatsRow struct {
	TotalJobs      int64       `json:"total_jobs"`
	NewJobsToday   int64       `json:"new_jobs_today"`
	LatestScrapeAt interface{} `json:"latest_scrape_at"`
}

func (q *Queries) GetJobStats(ctx context.Context) (GetJobStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobStats)
	var i GetJobStatsRow
	err := row.Scan(&i.TotalJobs, &i.NewJobsToday, &i.LatestScrapeAt)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT
    j.id,
    j.external_id,
    j.job_source,
    j.title,
    j.company_name,
    j.description,
    j.source_url,
    j.salary_min,
    j.salary_max,
    j.currency,
    j.job_location,
    j.is_remote,
    j.skills,
    j.logo_url,
    j.created_at,
    j.updated_at,
    m.match_score,
    m.title_score,
    m.skill_score,
    m.experience_score,
    m.matched_skills,
    m.missing_skills,
    m.ai_summary,
    m.is_enriched,
    m.created_at AS match_created_at,
    m.updated_at AS match_updated_at,
    (s.id IS NOT NULL)::BOOLEAN AS is_saved,
    (a.id IS NOT NULL)::BOOLEAN AS is_applied,
    (m.id IS NOT NULL)::BOOLEAN AS is_matched
FROM jobs AS j
LEFT JOIN saved_jobs AS s ON j.id = s.job_id AND s.user_id = $1
LEFT JOIN applications AS a ON j.id = a.job_id AND a.user_id = $1
LEFT JOIN user_job_matches AS m ON j.id = m.job_id AND m.user_id = $1
ORDER BY j.created_at DESC
`

type GetJobsRow struct {
	ID              uuid.UUID     `json:"id"`
	ExternalID      string        `json:"external_id"`
	JobSource       string        `json:"job_source"`
	Title           string        `json:"title"`
	CompanyName     string        `json:"company_name"`
	Description     *string       `json:"description"`
	SourceUrl       string        `json:"source_url"`
	SalaryMin       *int32        `json:"salary_min"`
	SalaryMax       *int32        `json:"salary_max"`
	Currency        *string       `json:"currency"`
	JobLocation     *string       `json:"job_location"`
	IsRemote        *bool         `json:"is_remote"`
	Skills          []string      `json:"skills"`
	LogoUrl         *string       `json:"logo_url"`
	CreatedAt       *time.Time    `json:"created_at"`
	UpdatedAt       *time.Time    `json:"updated_at"`
	MatchScore      *int32        `json:"match_score"`
	TitleScore      pgtype.Float8 `json:"title_score"`
	SkillScore      pgtype.Float8 `json:"skill_score"`
	ExperienceScore pgtype.Float8 `json:"experience_score"`
	MatchedSkills   []string      `json:"matched_skills"`
	MissingSkills   []string      `json:"missing_skills"`
	AiSummary       *string       `json:"ai_summary"`
	IsEnriched      *bool         `json:"is_enriched"`
	MatchCreatedAt  *time.Time    `json:"match_created_at"`
	MatchUpdatedAt  *time.Time    `json:"match_updated_at"`
	IsSaved         bool          `json:"is_saved"`
	IsApplied       bool          `json:"is_applied"`
	IsMatched       bool          `json:"is_matched"`
}

func (q *Queries) GetJobs(ctx context.Context, userID uuid.UUID) ([]GetJobsRow, error) {
	rows, err := q.db.Query(ctx, getJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobsRow
	for rows.Next() {
		var i GetJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.JobSource,
			&i.Title,
			&i.CompanyName,
			&i.Description,
			&i.SourceUrl,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.Currency,
			&i.JobLocation,
			&i.IsRemote,
			&i.Skills,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchScore,
			&i.TitleScore,
			&i.SkillScore,
			&i.ExperienceScore,
			&i.MatchedSkills,
			&i.MissingSkills,
			&i.AiSummary,
			&i.IsEnriched,
			&i.MatchCreatedAt,
			&i.MatchUpdatedAt,
			&i.IsSaved,
			&i.IsApplied,
			&i.IsMatched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    id,
    external_id,
    job_source,
    title,
    company_name,
    description,
    source_url,
    salary_min,
    salary_max,
    currency,
    job_location,
    is_remote,
    skills,
    logo_url,
    created_at,
    updated_at
FROM jobs
WHERE
    (title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
    AND ($2::TEXT IS NULL OR $2 = ANY(skills))
ORDER BY created_at DESC
`

type SearchJobsParams struct {
	Column1 *string `json:"column_1"`
	Column2 string  `json:"column_2"`
}

type SearchJobsRow struct {
	ID          uuid.UUID  `json:"id"`
	ExternalID  string     `json:"external_id"`
	JobSource   string     `json:"job_source"`
	Title       string     `json:"title"`
	CompanyName string     `json:"company_name"`
	Description *string    `json:"description"`
	SourceUrl   string     `json:"source_url"`
	SalaryMin   *int32     `json:"salary_min"`
	SalaryMax   *int32     `json:"salary_max"`
	Currency    *string    `json:"currency"`
	JobLocation *string    `json:"job_location"`
	IsRemote    *bool      `json:"is_remote"`
	Skills      []string   `json:"skills"`
	LogoUrl     *string    `json:"logo_url"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]SearchJobsRow, error) {
	rows, err := q.db.Query(ctx, searchJobs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJobsRow
	for rows.Next() {
		var i SearchJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.JobSource,
			&i.Title,
			&i.CompanyName,
			&i.Description,
			&i.SourceUrl,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.Currency,
			&i.JobLocation,
			&i.IsRemote,
			&i.Skills,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
