// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    external_id, source, title, company, description, url,
    salary_min, salary_max, currency, location, is_remote, skills, logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (external_id, source) DO NOTHING
RETURNING id, external_id, source, title, company, description, url, salary_min, salary_max, currency, location, is_remote, status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url
`

type CreateJobParams struct {
	ExternalID  string   `json:"external_id"`
	Source      string   `json:"source"`
	Title       string   `json:"title"`
	Company     string   `json:"company"`
	Description *string  `json:"description"`
	Url         string   `json:"url"`
	SalaryMin   *int32   `json:"salary_min"`
	SalaryMax   *int32   `json:"salary_max"`
	Currency    *string  `json:"currency"`
	Location    *string  `json:"location"`
	IsRemote    *bool    `json:"is_remote"`
	Skills      []string `json:"skills"`
	LogoUrl     *string  `json:"logo_url"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ExternalID,
		arg.Source,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.Url,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.Currency,
		arg.Location,
		arg.IsRemote,
		arg.Skills,
		arg.LogoUrl,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.Url,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.Currency,
		&i.Location,
		&i.IsRemote,
		&i.Status,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Skills,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, external_id, source, title, company, description, url, salary_min, salary_max, currency, location, is_remote, status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Description,
		&i.Url,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.Currency,
		&i.Location,
		&i.IsRemote,
		&i.Status,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Skills,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, external_id, source, title, company, description, url, salary_min, salary_max, currency, location, is_remote, status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Company,
			&i.Description,
			&i.Url,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.Currency,
			&i.Location,
			&i.IsRemote,
			&i.Status,
			&i.EmploymentType,
			&i.ExperienceLevel,
			&i.Skills,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobs = `-- name: SearchJobs :many
SELECT id, external_id, source, title, company, description, url, salary_min, salary_max, currency, location, is_remote, status, employment_type, experience_level, skills, posted_at, expires_at, created_at, updated_at, logo_url FROM jobs
WHERE
    (title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
    AND ($2::TEXT IS NULL OR $2 = ANY(skills))
ORDER BY created_at DESC
`

type SearchJobsParams struct {
	Column1 *string `json:"column_1"`
	Column2 string  `json:"column_2"`
}

func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, searchJobs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Company,
			&i.Description,
			&i.Url,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.Currency,
			&i.Location,
			&i.IsRemote,
			&i.Status,
			&i.EmploymentType,
			&i.ExperienceLevel,
			&i.Skills,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
