// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM user_job_matches
WHERE user_id = $1 AND job_id = $2
`

type DeleteMatchParams struct {
	UserID uuid.UUID `json:"user_id"`
	JobID  uuid.UUID `json:"job_id"`
}

func (q *Queries) DeleteMatch(ctx context.Context, arg DeleteMatchParams) error {
	_, err := q.db.Exec(ctx, deleteMatch, arg.UserID, arg.JobID)
	return err
}

const updateMatchEnrichment = `-- name: UpdateMatchEnrichment :exec
UPDATE user_job_matches
SET
    ai_summary = $3,
    is_enriched = TRUE,
    updated_at = NOW()
WHERE user_id = $1 AND job_id = $2
`

type UpdateMatchEnrichmentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	JobID     uuid.UUID `json:"job_id"`
	AiSummary *string   `json:"ai_summary"`
}

func (q *Queries) UpdateMatchEnrichment(ctx context.Context, arg UpdateMatchEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateMatchEnrichment, arg.UserID, arg.JobID, arg.AiSummary)
	return err
}

const upsertMatch = `-- name: UpsertMatch :exec
INSERT INTO user_job_matches (
    user_id,
    job_id,
    match_score,
    title_score,
    skill_score,
    experience_score,
    matched_skills,
    missing_skills,
    ai_summary,
    is_enriched
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (user_id, job_id) DO UPDATE SET
    match_score = excluded.match_score,
    title_score = excluded.title_score,
    skill_score = excluded.skill_score,
    experience_score = excluded.experience_score,
    matched_skills = excluded.matched_skills,
    missing_skills = excluded.missing_skills,
    ai_summary = excluded.ai_summary,
    is_enriched = excluded.is_enriched,
    updated_at = NOW()
`

type UpsertMatchParams struct {
	UserID          uuid.UUID     `json:"user_id"`
	JobID           uuid.UUID     `json:"job_id"`
	MatchScore      *int32        `json:"match_score"`
	TitleScore      pgtype.Float8 `json:"title_score"`
	SkillScore      pgtype.Float8 `json:"skill_score"`
	ExperienceScore pgtype.Float8 `json:"experience_score"`
	MatchedSkills   []string      `json:"matched_skills"`
	MissingSkills   []string      `json:"missing_skills"`
	AiSummary       *string       `json:"ai_summary"`
	IsEnriched      *bool         `json:"is_enriched"`
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) error {
	_, err := q.db.Exec(ctx, upsertMatch,
		arg.UserID,
		arg.JobID,
		arg.MatchScore,
		arg.TitleScore,
		arg.SkillScore,
		arg.ExperienceScore,
		arg.MatchedSkills,
		arg.MissingSkills,
		arg.AiSummary,
		arg.IsEnriched,
	)
	return err
}
