// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID              uuid.UUID      `json:"id"`
	ExternalID      string         `json:"external_id"`
	Source          string         `json:"source"`
	Title           string         `json:"title"`
	Company         string         `json:"company"`
	Description     sql.NullString `json:"description"`
	Url             string         `json:"url"`
	SalaryMin       sql.NullInt32  `json:"salary_min"`
	SalaryMax       sql.NullInt32  `json:"salary_max"`
	Currency        sql.NullString `json:"currency"`
	Location        sql.NullString `json:"location"`
	IsRemote        sql.NullBool   `json:"is_remote"`
	Status          sql.NullString `json:"status"`
	EmploymentType  sql.NullString `json:"employment_type"`
	ExperienceLevel sql.NullString `json:"experience_level"`
	Skills          []string       `json:"skills"`
	PostedAt        sql.NullTime   `json:"posted_at"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	LogoUrl         sql.NullString `json:"logo_url"`
}

type ServiceHealth struct {
	ID              uuid.UUID      `json:"id"`
	ServiceName     string         `json:"service_name"`
	LastRunAt       time.Time      `json:"last_run_at"`
	LastSuccessAt   sql.NullTime   `json:"last_success_at"`
	Status          string         `json:"status"`
	LastError       sql.NullString `json:"last_error"`
	JobCountLastRun sql.NullInt32  `json:"job_count_last_run"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}
