// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	JobID               uuid.UUID          `json:"job_id"`
	Status              string             `json:"status"`
	AppliedAt           *time.Time         `json:"applied_at"`
	LastStatusChangedAt pgtype.Timestamptz `json:"last_status_changed_at"`
	FollowUpAt          *time.Time         `json:"follow_up_at"`
	Notes               *string            `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID              uuid.UUID  `json:"id"`
	ExternalID      string     `json:"external_id"`
	Source          string     `json:"source"`
	Title           string     `json:"title"`
	Company         string     `json:"company"`
	Description     *string    `json:"description"`
	Url             string     `json:"url"`
	SalaryMin       *int32     `json:"salary_min"`
	SalaryMax       *int32     `json:"salary_max"`
	Currency        *string    `json:"currency"`
	Location        *string    `json:"location"`
	IsRemote        *bool      `json:"is_remote"`
	Status          *string    `json:"status"`
	EmploymentType  *string    `json:"employment_type"`
	ExperienceLevel *string    `json:"experience_level"`
	Skills          []string   `json:"skills"`
	PostedAt        *time.Time `json:"posted_at"`
	ExpiresAt       *time.Time `json:"expires_at"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
	LogoUrl         *string    `json:"logo_url"`
}

type SavedJob struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	JobID     uuid.UUID          `json:"job_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ServiceHealth struct {
	ID              uuid.UUID          `json:"id"`
	ServiceName     string             `json:"service_name"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	LastSuccessAt   *time.Time         `json:"last_success_at"`
	Status          string             `json:"status"`
	LastError       *string            `json:"last_error"`
	JobCountLastRun *int32             `json:"job_count_last_run"`
	UpdatedAt       *time.Time         `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	Email     string     `json:"email"`
	Username  *string    `json:"username"`
	Name      *string    `json:"name"`
	AvatarUrl *string    `json:"avatar_url"`
	IsAdmin   *bool      `json:"is_admin"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type UserAccount struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Provider     string     `json:"provider"`
	ProviderID   string     `json:"provider_id"`
	AccessToken  *string    `json:"access_token"`
	RefreshToken *string    `json:"refresh_token"`
	ExpiresAt    *time.Time `json:"expires_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
