// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSkillToExperience = `-- name: AddSkillToExperience :one
INSERT INTO experience_skills (
    experience_id, skill_id
) VALUES ($1, $2)
RETURNING experience_id, skill_id, created_at, updated_at
`

type AddSkillToExperienceParams struct {
	ExperienceID uuid.UUID `json:"experience_id"`
	SkillID      uuid.UUID `json:"skill_id"`
}

func (q *Queries) AddSkillToExperience(ctx context.Context, arg AddSkillToExperienceParams) (ExperienceSkill, error) {
	row := q.db.QueryRow(ctx, addSkillToExperience, arg.ExperienceID, arg.SkillID)
	var i ExperienceSkill
	err := row.Scan(
		&i.ExperienceID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserExperience = `-- name: CreateUserExperience :one
INSERT INTO user_experiences (
    user_id,
    company_name,
    company_url,
    role_title,
    exp_location,
    industry,
    employment_type,
    description,
    achievements,
    start_date,
    end_date,
    is_current
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, company_name, company_url, role_title, exp_location, industry, employment_type, description, achievements, start_date, end_date, is_current, created_at, updated_at
`

type CreateUserExperienceParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    string      `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      string      `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      *bool       `json:"is_current"`
}

func (q *Queries) CreateUserExperience(ctx context.Context, arg CreateUserExperienceParams) (UserExperience, error) {
	row := q.db.QueryRow(ctx, createUserExperience,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyUrl,
		arg.RoleTitle,
		arg.ExpLocation,
		arg.Industry,
		arg.EmploymentType,
		arg.Description,
		arg.Achievements,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var i UserExperience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyUrl,
		&i.RoleTitle,
		&i.ExpLocation,
		&i.Industry,
		&i.EmploymentType,
		&i.Description,
		&i.Achievements,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillsByExperienceID = `-- name: DeleteSkillsByExperienceID :exec
DELETE FROM experience_skills
WHERE experience_id = $1
`

func (q *Queries) DeleteSkillsByExperienceID(ctx context.Context, experienceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillsByExperienceID, experienceID)
	return err
}

const deleteUserExperience = `-- name: DeleteUserExperience :exec
DELETE FROM user_experiences
WHERE id = $1 AND user_id = $2
`

type DeleteUserExperienceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserExperience(ctx context.Context, arg DeleteUserExperienceParams) error {
	_, err := q.db.Exec(ctx, deleteUserExperience, arg.ID, arg.UserID)
	return err
}

const getExperiencesByUserID = `-- name: GetExperiencesByUserID :many
SELECT
    e.id,
    e.user_id,
    e.company_name,
    e.company_url,
    e.role_title,
    e.exp_location,
    e.industry,
    e.employment_type,
    e.description,
    e.achievements,
    e.start_date,
    e.end_date,
    e.is_current,
    e.created_at,
    e.updated_at,
    COALESCE(
        JSON_AGG(
            JSON_BUILD_OBJECT('id', s.id, 'name', s.name)
        ) FILTER (WHERE s.id IS NOT NULL), '[]'
    ) AS skills
FROM user_experiences AS e
LEFT JOIN experience_skills AS es ON e.id = es.experience_id
LEFT JOIN skills AS s ON es.skill_id = s.id
WHERE e.user_id = $1
GROUP BY e.id
ORDER BY e.start_date DESC
`

type GetExperiencesByUserIDRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    string      `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      string      `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      *bool       `json:"is_current"`
	CreatedAt      *time.Time  `json:"created_at"`
	UpdatedAt      *time.Time  `json:"updated_at"`
	Skills         interface{} `json:"skills"`
}

func (q *Queries) GetExperiencesByUserID(ctx context.Context, userID uuid.UUID) ([]GetExperiencesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExperiencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExperiencesByUserIDRow
	for rows.Next() {
		var i GetExperiencesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyUrl,
			&i.RoleTitle,
			&i.ExpLocation,
			&i.Industry,
			&i.EmploymentType,
			&i.Description,
			&i.Achievements,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateSkill = `-- name: GetOrCreateSkill :one
INSERT INTO skills (
    name
) VALUES ($1)
ON CONFLICT (name)
DO UPDATE SET name = excluded.name
RETURNING id
`

// This is a "fake" update just to get the id back
func (q *Queries) GetOrCreateSkill(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateSkill, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUserExperience = `-- name: UpdateUserExperience :one
UPDATE user_experiences
SET
    company_name = COALESCE($3, company_name),
    company_url = COALESCE($4, company_url),
    role_title = COALESCE($5, role_title),
    exp_location = COALESCE($6, exp_location),
    industry = COALESCE($7, industry),
    employment_type = COALESCE($8, employment_type),
    description = COALESCE($9, description),
    achievements = COALESCE($10, achievements),
    start_date = COALESCE($11, start_date),
    end_date = CASE
        WHEN $12 = TRUE THEN NULL
        ELSE COALESCE($13, end_date)
    END,
    is_current = COALESCE($12, is_current),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, company_name, company_url, role_title, exp_location, industry, employment_type, description, achievements, start_date, end_date, is_current, created_at, updated_at
`

type UpdateUserExperienceParams struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    *string     `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      *string     `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	IsCurrent      interface{} `json:"is_current"`
	EndDate        pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateUserExperience(ctx context.Context, arg UpdateUserExperienceParams) (UserExperience, error) {
	row := q.db.QueryRow(ctx, updateUserExperience,
		arg.ID,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyUrl,
		arg.RoleTitle,
		arg.ExpLocation,
		arg.Industry,
		arg.EmploymentType,
		arg.Description,
		arg.Achievements,
		arg.StartDate,
		arg.IsCurrent,
		arg.EndDate,
	)
	var i UserExperience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyUrl,
		&i.RoleTitle,
		&i.ExpLocation,
		&i.Industry,
		&i.EmploymentType,
		&i.Description,
		&i.Achievements,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
