// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDesiredLocation = `-- name: AddDesiredLocation :one
INSERT INTO user_desired_locations (
    user_id,
    location_name,
    is_remote,
    priority
) VALUES (
    $1, $2, $3, $4
)
RETURNING user_id, location_name, is_remote, priority
`

type AddDesiredLocationParams struct {
	UserID       uuid.UUID `json:"user_id"`
	LocationName string    `json:"location_name"`
	IsRemote     *bool     `json:"is_remote"`
	Priority     *int32    `json:"priority"`
}

func (q *Queries) AddDesiredLocation(ctx context.Context, arg AddDesiredLocationParams) (UserDesiredLocation, error) {
	row := q.db.QueryRow(ctx, addDesiredLocation,
		arg.UserID,
		arg.LocationName,
		arg.IsRemote,
		arg.Priority,
	)
	var i UserDesiredLocation
	err := row.Scan(
		&i.UserID,
		&i.LocationName,
		&i.IsRemote,
		&i.Priority,
	)
	return i, err
}

const addDesiredRole = `-- name: AddDesiredRole :one
INSERT INTO user_desired_roles (
    user_id,
    role_title,
    priority
) VALUES (
    $1, $2, $3
)
RETURNING user_id, role_title, priority
`

type AddDesiredRoleParams struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleTitle string    `json:"role_title"`
	Priority  *int32    `json:"priority"`
}

func (q *Queries) AddDesiredRole(ctx context.Context, arg AddDesiredRoleParams) (UserDesiredRole, error) {
	row := q.db.QueryRow(ctx, addDesiredRole, arg.UserID, arg.RoleTitle, arg.Priority)
	var i UserDesiredRole
	err := row.Scan(&i.UserID, &i.RoleTitle, &i.Priority)
	return i, err
}

const addSkillToExperience = `-- name: AddSkillToExperience :one
INSERT INTO experience_skills (
    experience_id, skill_id
) VALUES ($1, $2)
RETURNING experience_id, skill_id, created_at, updated_at
`

type AddSkillToExperienceParams struct {
	ExperienceID uuid.UUID `json:"experience_id"`
	SkillID      uuid.UUID `json:"skill_id"`
}

func (q *Queries) AddSkillToExperience(ctx context.Context, arg AddSkillToExperienceParams) (ExperienceSkill, error) {
	row := q.db.QueryRow(ctx, addSkillToExperience, arg.ExperienceID, arg.SkillID)
	var i ExperienceSkill
	err := row.Scan(
		&i.ExperienceID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSkillToUser = `-- name: AddSkillToUser :one
INSERT INTO user_skills (
    user_id,
    skill_id,
    proficiency,
    years_experience,
    is_featured,
    endorsed_by_ai,
    display_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING user_id, skill_id, proficiency, years_experience, is_featured, endorsed_by_ai, display_order, created_at, updated_at
`

type AddSkillToUserParams struct {
	UserID          uuid.UUID `json:"user_id"`
	SkillID         uuid.UUID `json:"skill_id"`
	Proficiency     *string   `json:"proficiency"`
	YearsExperience *int32    `json:"years_experience"`
	IsFeatured      *bool     `json:"is_featured"`
	EndorsedByAi    *bool     `json:"endorsed_by_ai"`
	DisplayOrder    *int32    `json:"display_order"`
}

func (q *Queries) AddSkillToUser(ctx context.Context, arg AddSkillToUserParams) (UserSkill, error) {
	row := q.db.QueryRow(ctx, addSkillToUser,
		arg.UserID,
		arg.SkillID,
		arg.Proficiency,
		arg.YearsExperience,
		arg.IsFeatured,
		arg.EndorsedByAi,
		arg.DisplayOrder,
	)
	var i UserSkill
	err := row.Scan(
		&i.UserID,
		&i.SkillID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsFeatured,
		&i.EndorsedByAi,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearUserDesiredLocations = `-- name: ClearUserDesiredLocations :exec
DELETE FROM user_desired_locations
WHERE user_id = $1
`

func (q *Queries) ClearUserDesiredLocations(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserDesiredLocations, userID)
	return err
}

const clearUserDesiredRoles = `-- name: ClearUserDesiredRoles :exec
DELETE FROM user_desired_roles
WHERE user_id = $1
`

func (q *Queries) ClearUserDesiredRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserDesiredRoles, userID)
	return err
}

const clearUserSkills = `-- name: ClearUserSkills :exec
DELETE FROM user_skills
WHERE user_id = $1
`

func (q *Queries) ClearUserSkills(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserSkills, userID)
	return err
}

const createUserCertification = `-- name: CreateUserCertification :one
INSERT INTO user_certifications (
    user_id,
    certification_name,
    issuing_organization,
    issue_date,
    expiration_date,
    does_not_expire,
    credential_id,
    credential_url,
    is_in_progress
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, certification_name, issuing_organization, issue_date, expiration_date, does_not_expire, credential_id, credential_url, is_in_progress, certification_location, created_at, updated_at
`

type CreateUserCertificationParams struct {
	UserID              uuid.UUID   `json:"user_id"`
	CertificationName   string      `json:"certification_name"`
	IssuingOrganization string      `json:"issuing_organization"`
	IssueDate           pgtype.Date `json:"issue_date"`
	ExpirationDate      pgtype.Date `json:"expiration_date"`
	DoesNotExpire       *bool       `json:"does_not_expire"`
	CredentialID        *string     `json:"credential_id"`
	CredentialUrl       *string     `json:"credential_url"`
	IsInProgress        *bool       `json:"is_in_progress"`
}

func (q *Queries) CreateUserCertification(ctx context.Context, arg CreateUserCertificationParams) (UserCertification, error) {
	row := q.db.QueryRow(ctx, createUserCertification,
		arg.UserID,
		arg.CertificationName,
		arg.IssuingOrganization,
		arg.IssueDate,
		arg.ExpirationDate,
		arg.DoesNotExpire,
		arg.CredentialID,
		arg.CredentialUrl,
		arg.IsInProgress,
	)
	var i UserCertification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CertificationName,
		&i.IssuingOrganization,
		&i.IssueDate,
		&i.ExpirationDate,
		&i.DoesNotExpire,
		&i.CredentialID,
		&i.CredentialUrl,
		&i.IsInProgress,
		&i.CertificationLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserEducation = `-- name: CreateUserEducation :one
INSERT INTO user_education (
    user_id,
    institution_name,
    degree_type,
    degree_name,
    field_of_study,
    start_date,
    end_date,
    is_current,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, institution_name, degree_type, degree_name, field_of_study, start_date, end_date, is_current, description, is_highlighted, created_at, updated_at
`

type CreateUserEducationParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	InstitutionName string      `json:"institution_name"`
	DegreeType      *string     `json:"degree_type"`
	DegreeName      *string     `json:"degree_name"`
	FieldOfStudy    *string     `json:"field_of_study"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	IsCurrent       *bool       `json:"is_current"`
	Description     *string     `json:"description"`
}

func (q *Queries) CreateUserEducation(ctx context.Context, arg CreateUserEducationParams) (UserEducation, error) {
	row := q.db.QueryRow(ctx, createUserEducation,
		arg.UserID,
		arg.InstitutionName,
		arg.DegreeType,
		arg.DegreeName,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
		arg.Description,
	)
	var i UserEducation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.DegreeType,
		&i.DegreeName,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.Description,
		&i.IsHighlighted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserExperience = `-- name: CreateUserExperience :one
INSERT INTO user_experiences (
    user_id,
    company_name,
    company_url,
    role_title,
    exp_location,
    industry,
    employment_type,
    description,
    achievements,
    start_date,
    end_date,
    is_current
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, company_name, company_url, role_title, exp_location, industry, employment_type, description, achievements, start_date, end_date, is_current, created_at, updated_at
`

type CreateUserExperienceParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    string      `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      string      `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      *bool       `json:"is_current"`
}

func (q *Queries) CreateUserExperience(ctx context.Context, arg CreateUserExperienceParams) (UserExperience, error) {
	row := q.db.QueryRow(ctx, createUserExperience,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyUrl,
		arg.RoleTitle,
		arg.ExpLocation,
		arg.Industry,
		arg.EmploymentType,
		arg.Description,
		arg.Achievements,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var i UserExperience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyUrl,
		&i.RoleTitle,
		&i.ExpLocation,
		&i.Industry,
		&i.EmploymentType,
		&i.Description,
		&i.Achievements,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserLanguage = `-- name: CreateUserLanguage :one
INSERT INTO user_languages (
    user_id,
    user_language,
    proficiency
) VALUES (
    $1, $2, $3
)
RETURNING user_id, user_language, proficiency, created_at, updated_at
`

type CreateUserLanguageParams struct {
	UserID       uuid.UUID `json:"user_id"`
	UserLanguage string    `json:"user_language"`
	Proficiency  *string   `json:"proficiency"`
}

func (q *Queries) CreateUserLanguage(ctx context.Context, arg CreateUserLanguageParams) (UserLanguage, error) {
	row := q.db.QueryRow(ctx, createUserLanguage, arg.UserID, arg.UserLanguage, arg.Proficiency)
	var i UserLanguage
	err := row.Scan(
		&i.UserID,
		&i.UserLanguage,
		&i.Proficiency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProject = `-- name: CreateUserProject :one
INSERT INTO user_projects (
    user_id,
    title,
    role_title,
    description,
    impact,
    project_url,
    repository_url,
    start_date,
    end_date,
    is_current,
    is_featured
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, title, role_title, description, impact, project_url, repository_url, start_date, end_date, is_current, is_featured, created_at, updated_at
`

type CreateUserProjectParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Title         string      `json:"title"`
	RoleTitle     *string     `json:"role_title"`
	Description   *string     `json:"description"`
	Impact        *string     `json:"impact"`
	ProjectUrl    *string     `json:"project_url"`
	RepositoryUrl *string     `json:"repository_url"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	IsCurrent     *bool       `json:"is_current"`
	IsFeatured    *bool       `json:"is_featured"`
}

func (q *Queries) CreateUserProject(ctx context.Context, arg CreateUserProjectParams) (UserProject, error) {
	row := q.db.QueryRow(ctx, createUserProject,
		arg.UserID,
		arg.Title,
		arg.RoleTitle,
		arg.Description,
		arg.Impact,
		arg.ProjectUrl,
		arg.RepositoryUrl,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
		arg.IsFeatured,
	)
	var i UserProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.RoleTitle,
		&i.Description,
		&i.Impact,
		&i.ProjectUrl,
		&i.RepositoryUrl,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillsByExperienceID = `-- name: DeleteSkillsByExperienceID :exec
DELETE FROM experience_skills
WHERE experience_id = $1
`

func (q *Queries) DeleteSkillsByExperienceID(ctx context.Context, experienceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillsByExperienceID, experienceID)
	return err
}

const deleteUserCertification = `-- name: DeleteUserCertification :exec
DELETE FROM user_certifications
WHERE id = $1 AND user_id = $2
`

type DeleteUserCertificationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserCertification(ctx context.Context, arg DeleteUserCertificationParams) error {
	_, err := q.db.Exec(ctx, deleteUserCertification, arg.ID, arg.UserID)
	return err
}

const deleteUserEducation = `-- name: DeleteUserEducation :exec
DELETE FROM user_education
WHERE id = $1 AND user_id = $2
`

type DeleteUserEducationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserEducation(ctx context.Context, arg DeleteUserEducationParams) error {
	_, err := q.db.Exec(ctx, deleteUserEducation, arg.ID, arg.UserID)
	return err
}

const deleteUserExperience = `-- name: DeleteUserExperience :exec
DELETE FROM user_experiences
WHERE id = $1 AND user_id = $2
`

type DeleteUserExperienceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserExperience(ctx context.Context, arg DeleteUserExperienceParams) error {
	_, err := q.db.Exec(ctx, deleteUserExperience, arg.ID, arg.UserID)
	return err
}

const deleteUserLanguage = `-- name: DeleteUserLanguage :exec
DELETE FROM user_languages
WHERE user_id = $1 AND user_language = $2
`

type DeleteUserLanguageParams struct {
	UserID       uuid.UUID `json:"user_id"`
	UserLanguage string    `json:"user_language"`
}

func (q *Queries) DeleteUserLanguage(ctx context.Context, arg DeleteUserLanguageParams) error {
	_, err := q.db.Exec(ctx, deleteUserLanguage, arg.UserID, arg.UserLanguage)
	return err
}

const deleteUserProject = `-- name: DeleteUserProject :exec
DELETE FROM user_projects
WHERE id = $1 AND user_id = $2
`

type DeleteUserProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserProject(ctx context.Context, arg DeleteUserProjectParams) error {
	_, err := q.db.Exec(ctx, deleteUserProject, arg.ID, arg.UserID)
	return err
}

const getCertificationsByUserID = `-- name: GetCertificationsByUserID :many
SELECT
    id,
    user_id,
    certification_name,
    issuing_organization,
    issue_date,
    expiration_date,
    does_not_expire,
    credential_id,
    credential_url,
    is_in_progress,
    created_at,
    updated_at
FROM user_certifications
WHERE user_id = $1
ORDER BY issue_date DESC
`

type GetCertificationsByUserIDRow struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	CertificationName   string      `json:"certification_name"`
	IssuingOrganization string      `json:"issuing_organization"`
	IssueDate           pgtype.Date `json:"issue_date"`
	ExpirationDate      pgtype.Date `json:"expiration_date"`
	DoesNotExpire       *bool       `json:"does_not_expire"`
	CredentialID        *string     `json:"credential_id"`
	CredentialUrl       *string     `json:"credential_url"`
	IsInProgress        *bool       `json:"is_in_progress"`
	CreatedAt           *time.Time  `json:"created_at"`
	UpdatedAt           *time.Time  `json:"updated_at"`
}

func (q *Queries) GetCertificationsByUserID(ctx context.Context, userID uuid.UUID) ([]GetCertificationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getCertificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCertificationsByUserIDRow
	for rows.Next() {
		var i GetCertificationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CertificationName,
			&i.IssuingOrganization,
			&i.IssueDate,
			&i.ExpirationDate,
			&i.DoesNotExpire,
			&i.CredentialID,
			&i.CredentialUrl,
			&i.IsInProgress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEducationsByUserID = `-- name: GetEducationsByUserID :many
SELECT
    id,
    user_id,
    institution_name,
    degree_type,
    degree_name,
    field_of_study,
    start_date,
    end_date,
    is_current,
    description,
    created_at,
    updated_at
FROM user_education
WHERE user_id = $1
ORDER BY start_date DESC
`

type GetEducationsByUserIDRow struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	InstitutionName string      `json:"institution_name"`
	DegreeType      *string     `json:"degree_type"`
	DegreeName      *string     `json:"degree_name"`
	FieldOfStudy    *string     `json:"field_of_study"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	IsCurrent       *bool       `json:"is_current"`
	Description     *string     `json:"description"`
	CreatedAt       *time.Time  `json:"created_at"`
	UpdatedAt       *time.Time  `json:"updated_at"`
}

func (q *Queries) GetEducationsByUserID(ctx context.Context, userID uuid.UUID) ([]GetEducationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getEducationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEducationsByUserIDRow
	for rows.Next() {
		var i GetEducationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstitutionName,
			&i.DegreeType,
			&i.DegreeName,
			&i.FieldOfStudy,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExperienceByID = `-- name: GetExperienceByID :one
SELECT
    e.id,
    e.user_id,
    e.company_name,
    e.company_url,
    e.role_title,
    e.exp_location,
    e.industry,
    e.employment_type,
    e.description,
    e.achievements,
    e.start_date,
    e.end_date,
    e.is_current,
    e.created_at,
    e.updated_at,
    COALESCE(
        JSON_AGG(
            JSON_BUILD_OBJECT('id', s.id, 'skill_name', s.skill_name)
        ) FILTER (WHERE s.id IS NOT NULL), '[]'
    ) AS skills
FROM user_experiences AS e
LEFT JOIN experience_skills AS es ON e.id = es.experience_id
LEFT JOIN skills AS s ON es.skill_id = s.id
WHERE e.id = $1 AND e.user_id = $2
GROUP BY e.id
`

type GetExperienceByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetExperienceByIDRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    string      `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      string      `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      *bool       `json:"is_current"`
	CreatedAt      *time.Time  `json:"created_at"`
	UpdatedAt      *time.Time  `json:"updated_at"`
	Skills         interface{} `json:"skills"`
}

func (q *Queries) GetExperienceByID(ctx context.Context, arg GetExperienceByIDParams) (GetExperienceByIDRow, error) {
	row := q.db.QueryRow(ctx, getExperienceByID, arg.ID, arg.UserID)
	var i GetExperienceByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyUrl,
		&i.RoleTitle,
		&i.ExpLocation,
		&i.Industry,
		&i.EmploymentType,
		&i.Description,
		&i.Achievements,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Skills,
	)
	return i, err
}

const getExperiencesByUserID = `-- name: GetExperiencesByUserID :many
SELECT
    e.id,
    e.user_id,
    e.company_name,
    e.company_url,
    e.role_title,
    e.exp_location,
    e.industry,
    e.employment_type,
    e.description,
    e.achievements,
    e.start_date,
    e.end_date,
    e.is_current,
    e.created_at,
    e.updated_at,
    COALESCE(
        JSON_AGG(
            JSON_BUILD_OBJECT('id', s.id, 'skill_name', s.skill_name)
        ) FILTER (WHERE s.id IS NOT NULL), '[]'
    ) AS skills
FROM user_experiences AS e
LEFT JOIN experience_skills AS es ON e.id = es.experience_id
LEFT JOIN skills AS s ON es.skill_id = s.id
WHERE e.user_id = $1
GROUP BY e.id
ORDER BY e.start_date DESC
`

type GetExperiencesByUserIDRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    string      `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      string      `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      *bool       `json:"is_current"`
	CreatedAt      *time.Time  `json:"created_at"`
	UpdatedAt      *time.Time  `json:"updated_at"`
	Skills         interface{} `json:"skills"`
}

func (q *Queries) GetExperiencesByUserID(ctx context.Context, userID uuid.UUID) ([]GetExperiencesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExperiencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExperiencesByUserIDRow
	for rows.Next() {
		var i GetExperiencesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyUrl,
			&i.RoleTitle,
			&i.ExpLocation,
			&i.Industry,
			&i.EmploymentType,
			&i.Description,
			&i.Achievements,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Skills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLanguagesByUserID = `-- name: GetLanguagesByUserID :many
SELECT
    user_id,
    user_language,
    proficiency,
    created_at,
    updated_at
FROM user_languages
WHERE user_id = $1
ORDER BY proficiency DESC
`

func (q *Queries) GetLanguagesByUserID(ctx context.Context, userID uuid.UUID) ([]UserLanguage, error) {
	rows, err := q.db.Query(ctx, getLanguagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserLanguage
	for rows.Next() {
		var i UserLanguage
		if err := rows.Scan(
			&i.UserID,
			&i.UserLanguage,
			&i.Proficiency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateSkill = `-- name: GetOrCreateSkill :one
INSERT INTO skills (
    skill_name
) VALUES ($1)
ON CONFLICT (skill_name)
DO UPDATE SET skill_name = excluded.skill_name
RETURNING id
`

// This is a "fake" update just to get the id back
func (q *Queries) GetOrCreateSkill(ctx context.Context, skillName string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateSkill, skillName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectsByUserID = `-- name: GetProjectsByUserID :many
SELECT
    id,
    user_id,
    title,
    role_title,
    description,
    impact,
    project_url,
    repository_url,
    start_date,
    end_date,
    is_current,
    is_featured,
    created_at,
    updated_at
FROM user_projects
WHERE user_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetProjectsByUserID(ctx context.Context, userID uuid.UUID) ([]UserProject, error) {
	rows, err := q.db.Query(ctx, getProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProject
	for rows.Next() {
		var i UserProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.RoleTitle,
			&i.Description,
			&i.Impact,
			&i.ProjectUrl,
			&i.RepositoryUrl,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDesiredLocations = `-- name: GetUserDesiredLocations :many
SELECT
    location_name,
    is_remote,
    priority
FROM user_desired_locations
WHERE user_id = $1
ORDER BY priority ASC, location_name ASC
`

type GetUserDesiredLocationsRow struct {
	LocationName string `json:"location_name"`
	IsRemote     *bool  `json:"is_remote"`
	Priority     *int32 `json:"priority"`
}

func (q *Queries) GetUserDesiredLocations(ctx context.Context, userID uuid.UUID) ([]GetUserDesiredLocationsRow, error) {
	rows, err := q.db.Query(ctx, getUserDesiredLocations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDesiredLocationsRow
	for rows.Next() {
		var i GetUserDesiredLocationsRow
		if err := rows.Scan(&i.LocationName, &i.IsRemote, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDesiredRoles = `-- name: GetUserDesiredRoles :many
SELECT
    role_title,
    priority
FROM user_desired_roles
WHERE user_id = $1
ORDER BY priority ASC, role_title ASC
`

type GetUserDesiredRolesRow struct {
	RoleTitle string `json:"role_title"`
	Priority  *int32 `json:"priority"`
}

func (q *Queries) GetUserDesiredRoles(ctx context.Context, userID uuid.UUID) ([]GetUserDesiredRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserDesiredRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDesiredRolesRow
	for rows.Next() {
		var i GetUserDesiredRolesRow
		if err := rows.Scan(&i.RoleTitle, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSkillsByUserID = `-- name: GetUserSkillsByUserID :many
SELECT
    s.id AS skill_id,
    s.skill_name,
    s.category AS skill_category,
    us.proficiency,
    us.years_experience,
    us.is_featured,
    us.endorsed_by_ai,
    us.display_order
FROM user_skills AS us
INNER JOIN skills AS s ON us.skill_id = s.id
WHERE us.user_id = $1
ORDER BY us.display_order ASC, s.skill_name ASC
`

type GetUserSkillsByUserIDRow struct {
	SkillID         uuid.UUID `json:"skill_id"`
	SkillName       string    `json:"skill_name"`
	SkillCategory   *string   `json:"skill_category"`
	Proficiency     *string   `json:"proficiency"`
	YearsExperience *int32    `json:"years_experience"`
	IsFeatured      *bool     `json:"is_featured"`
	EndorsedByAi    *bool     `json:"endorsed_by_ai"`
	DisplayOrder    *int32    `json:"display_order"`
}

func (q *Queries) GetUserSkillsByUserID(ctx context.Context, userID uuid.UUID) ([]GetUserSkillsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserSkillsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSkillsByUserIDRow
	for rows.Next() {
		var i GetUserSkillsByUserIDRow
		if err := rows.Scan(
			&i.SkillID,
			&i.SkillName,
			&i.SkillCategory,
			&i.Proficiency,
			&i.YearsExperience,
			&i.IsFeatured,
			&i.EndorsedByAi,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserCertification = `-- name: UpdateUserCertification :one
UPDATE user_certifications
SET
    certification_name
    = COALESCE($3, certification_name),
    issuing_organization
    = COALESCE($4, issuing_organization),
    issue_date = COALESCE($5, issue_date),
    expiration_date = COALESCE($6, expiration_date),
    does_not_expire = COALESCE($7, does_not_expire),
    credential_id = COALESCE($8, credential_id),
    credential_url = COALESCE($9, credential_url),
    is_in_progress = COALESCE($10, is_in_progress),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, certification_name, issuing_organization, issue_date, expiration_date, does_not_expire, credential_id, credential_url, is_in_progress, certification_location, created_at, updated_at
`

type UpdateUserCertificationParams struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	CertificationName   *string     `json:"certification_name"`
	IssuingOrganization *string     `json:"issuing_organization"`
	IssueDate           pgtype.Date `json:"issue_date"`
	ExpirationDate      pgtype.Date `json:"expiration_date"`
	DoesNotExpire       *bool       `json:"does_not_expire"`
	CredentialID        *string     `json:"credential_id"`
	CredentialUrl       *string     `json:"credential_url"`
	IsInProgress        *bool       `json:"is_in_progress"`
}

func (q *Queries) UpdateUserCertification(ctx context.Context, arg UpdateUserCertificationParams) (UserCertification, error) {
	row := q.db.QueryRow(ctx, updateUserCertification,
		arg.ID,
		arg.UserID,
		arg.CertificationName,
		arg.IssuingOrganization,
		arg.IssueDate,
		arg.ExpirationDate,
		arg.DoesNotExpire,
		arg.CredentialID,
		arg.CredentialUrl,
		arg.IsInProgress,
	)
	var i UserCertification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CertificationName,
		&i.IssuingOrganization,
		&i.IssueDate,
		&i.ExpirationDate,
		&i.DoesNotExpire,
		&i.CredentialID,
		&i.CredentialUrl,
		&i.IsInProgress,
		&i.CertificationLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEducation = `-- name: UpdateUserEducation :one
UPDATE user_education
SET
    institution_name
    = COALESCE($3, institution_name),
    degree_type = COALESCE($4, degree_type),
    degree_name = COALESCE($5, degree_name),
    field_of_study = COALESCE($6, field_of_study),
    start_date = COALESCE($7::date, start_date),
    end_date = CASE
        WHEN $8::boolean = TRUE THEN NULL
        ELSE COALESCE($9::date, end_date)
    END,
    is_current = COALESCE($8::boolean, is_current),
    description = COALESCE($10, description),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, institution_name, degree_type, degree_name, field_of_study, start_date, end_date, is_current, description, is_highlighted, created_at, updated_at
`

type UpdateUserEducationParams struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	InstitutionName *string     `json:"institution_name"`
	DegreeType      *string     `json:"degree_type"`
	DegreeName      *string     `json:"degree_name"`
	FieldOfStudy    *string     `json:"field_of_study"`
	StartDate       pgtype.Date `json:"start_date"`
	IsCurrent       *bool       `json:"is_current"`
	EndDate         pgtype.Date `json:"end_date"`
	Description     *string     `json:"description"`
}

func (q *Queries) UpdateUserEducation(ctx context.Context, arg UpdateUserEducationParams) (UserEducation, error) {
	row := q.db.QueryRow(ctx, updateUserEducation,
		arg.ID,
		arg.UserID,
		arg.InstitutionName,
		arg.DegreeType,
		arg.DegreeName,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.IsCurrent,
		arg.EndDate,
		arg.Description,
	)
	var i UserEducation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.DegreeType,
		&i.DegreeName,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.Description,
		&i.IsHighlighted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserExperience = `-- name: UpdateUserExperience :one
UPDATE user_experiences
SET
    company_name = COALESCE($3, company_name),
    company_url = COALESCE($4, company_url),
    role_title = COALESCE($5, role_title),
    exp_location = COALESCE($6, exp_location),
    industry = COALESCE($7, industry),
    employment_type = COALESCE($8, employment_type),
    description = COALESCE($9, description),
    achievements = COALESCE($10, achievements),
    start_date = COALESCE($11, start_date),
    end_date = CASE
        WHEN $12::boolean = TRUE THEN NULL
        ELSE COALESCE($13::date, end_date)
    END,
    is_current = COALESCE($12, is_current),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, company_name, company_url, role_title, exp_location, industry, employment_type, description, achievements, start_date, end_date, is_current, created_at, updated_at
`

type UpdateUserExperienceParams struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	CompanyName    *string     `json:"company_name"`
	CompanyUrl     *string     `json:"company_url"`
	RoleTitle      *string     `json:"role_title"`
	ExpLocation    *string     `json:"exp_location"`
	Industry       *string     `json:"industry"`
	EmploymentType *string     `json:"employment_type"`
	Description    *string     `json:"description"`
	Achievements   []string    `json:"achievements"`
	StartDate      pgtype.Date `json:"start_date"`
	IsCurrent      *bool       `json:"is_current"`
	EndDate        pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateUserExperience(ctx context.Context, arg UpdateUserExperienceParams) (UserExperience, error) {
	row := q.db.QueryRow(ctx, updateUserExperience,
		arg.ID,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyUrl,
		arg.RoleTitle,
		arg.ExpLocation,
		arg.Industry,
		arg.EmploymentType,
		arg.Description,
		arg.Achievements,
		arg.StartDate,
		arg.IsCurrent,
		arg.EndDate,
	)
	var i UserExperience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyUrl,
		&i.RoleTitle,
		&i.ExpLocation,
		&i.Industry,
		&i.EmploymentType,
		&i.Description,
		&i.Achievements,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLanguage = `-- name: UpdateUserLanguage :one
UPDATE user_languages
SET
    proficiency = COALESCE($3, proficiency),
    updated_at = NOW()
WHERE user_id = $1 AND user_language = $2
RETURNING user_id, user_language, proficiency, created_at, updated_at
`

type UpdateUserLanguageParams struct {
	UserID       uuid.UUID `json:"user_id"`
	UserLanguage string    `json:"user_language"`
	Proficiency  *string   `json:"proficiency"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (UserLanguage, error) {
	row := q.db.QueryRow(ctx, updateUserLanguage, arg.UserID, arg.UserLanguage, arg.Proficiency)
	var i UserLanguage
	err := row.Scan(
		&i.UserID,
		&i.UserLanguage,
		&i.Proficiency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProject = `-- name: UpdateUserProject :one
UPDATE user_projects
SET
    title = COALESCE($3, title),
    role_title = COALESCE($4, role_title),
    description = COALESCE($5, description),
    impact = COALESCE($6, impact),
    project_url = COALESCE($7, project_url),
    repository_url = COALESCE($8, repository_url),
    start_date = COALESCE($9, start_date),
    end_date = CASE
        WHEN $10::boolean = TRUE THEN NULL
        ELSE COALESCE($11::date, end_date)
    END,
    is_current = COALESCE($10, is_current),
    is_featured = COALESCE($12, is_featured),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, role_title, description, impact, project_url, repository_url, start_date, end_date, is_current, is_featured, created_at, updated_at
`

type UpdateUserProjectParams struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Title         *string     `json:"title"`
	RoleTitle     *string     `json:"role_title"`
	Description   *string     `json:"description"`
	Impact        *string     `json:"impact"`
	ProjectUrl    *string     `json:"project_url"`
	RepositoryUrl *string     `json:"repository_url"`
	StartDate     pgtype.Date `json:"start_date"`
	IsCurrent     *bool       `json:"is_current"`
	EndDate       pgtype.Date `json:"end_date"`
	IsFeatured    *bool       `json:"is_featured"`
}

func (q *Queries) UpdateUserProject(ctx context.Context, arg UpdateUserProjectParams) (UserProject, error) {
	row := q.db.QueryRow(ctx, updateUserProject,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.RoleTitle,
		arg.Description,
		arg.Impact,
		arg.ProjectUrl,
		arg.RepositoryUrl,
		arg.StartDate,
		arg.IsCurrent,
		arg.EndDate,
		arg.IsFeatured,
	)
	var i UserProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.RoleTitle,
		&i.Description,
		&i.Impact,
		&i.ProjectUrl,
		&i.RepositoryUrl,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
