// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_jobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSavedJobsForUser = `-- name: GetSavedJobsForUser :many
SELECT s.id, j.id as job_id, j.title, j.company, j.location, j.is_remote, j.logo_url, a.status, s.created_at AS saved_at
FROM saved_jobs s
JOIN jobs j ON s.job_id = j.id
LEFT JOIN applications a ON s.job_id = a.job_id AND s.user_id = a.user_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type GetSavedJobsForUserRow struct {
	ID       uuid.UUID          `json:"id"`
	JobID    uuid.UUID          `json:"job_id"`
	Title    string             `json:"title"`
	Company  string             `json:"company"`
	Location *string            `json:"location"`
	IsRemote *bool              `json:"is_remote"`
	LogoUrl  *string            `json:"logo_url"`
	Status   *string            `json:"status"`
	SavedAt  pgtype.Timestamptz `json:"saved_at"`
}

func (q *Queries) GetSavedJobsForUser(ctx context.Context, userID uuid.UUID) ([]GetSavedJobsForUserRow, error) {
	rows, err := q.db.Query(ctx, getSavedJobsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedJobsForUserRow
	for rows.Next() {
		var i GetSavedJobsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.IsRemote,
			&i.LogoUrl,
			&i.Status,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :one
INSERT INTO saved_jobs (user_id, job_id)
VALUES ($1, $2)
RETURNING id, user_id, job_id, created_at
`

type SaveJobParams struct {
	UserID uuid.UUID `json:"user_id"`
	JobID  uuid.UUID `json:"job_id"`
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) (SavedJob, error) {
	row := q.db.QueryRow(ctx, saveJob, arg.UserID, arg.JobID)
	var i SavedJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const unSaveJob = `-- name: UnSaveJob :exec
DELETE FROM saved_jobs
WHERE id = $1 AND user_id = $2
`

type UnSaveJobParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnSaveJob(ctx context.Context, arg UnSaveJobParams) error {
	_, err := q.db.Exec(ctx, unSaveJob, arg.ID, arg.UserID)
	return err
}
