// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (
    user_id, auth_provider, auth_provider_id, access_token
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, auth_provider, auth_provider_id, access_token, refresh_token, expires_at, revoked_at, created_at, updated_at
`

type CreateUserAccountParams struct {
	UserID         uuid.UUID `json:"user_id"`
	AuthProvider   string    `json:"auth_provider"`
	AuthProviderID string    `json:"auth_provider_id"`
	AccessToken    *string   `json:"access_token"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.UserID,
		arg.AuthProvider,
		arg.AuthProviderID,
		arg.AccessToken,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
