// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (
    user_id, provider, provider_id, access_token
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, provider, provider_id, access_token, refresh_token, expires_at, revoked_at, created_at, updated_at
`

type CreateUserAccountParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Provider    string    `json:"provider"`
	ProviderID  string    `json:"provider_id"`
	AccessToken *string   `json:"access_token"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.AccessToken,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
