// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, username, full_name, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, username, full_name, avatar_url, phone, user_location, website_url, linkedin_url, github_url, headline, user_summary, availability, min_salary, max_salary, salary_currency, years_of_experience, preferred_job_types, preferred_industries, company_stage_preference, notify_jobs, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	FullName  *string `json:"full_name"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.UserLocation,
		&i.WebsiteUrl,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.Headline,
		&i.UserSummary,
		&i.Availability,
		&i.MinSalary,
		&i.MaxSalary,
		&i.SalaryCurrency,
		&i.YearsOfExperience,
		&i.PreferredJobTypes,
		&i.PreferredIndustries,
		&i.CompanyStagePreference,
		&i.NotifyJobs,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    username,
    full_name,
    avatar_url,
    phone,
    user_location,
    website_url,
    linkedin_url,
    github_url,
    headline,
    user_summary,
    availability,
    min_salary,
    max_salary,
    salary_currency,
    years_of_experience,
    preferred_job_types,
    preferred_industries,
    company_stage_preference,
    notify_jobs,
    is_admin,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.UserLocation,
		&i.WebsiteUrl,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.Headline,
		&i.UserSummary,
		&i.Availability,
		&i.MinSalary,
		&i.MaxSalary,
		&i.SalaryCurrency,
		&i.YearsOfExperience,
		&i.PreferredJobTypes,
		&i.PreferredIndustries,
		&i.CompanyStagePreference,
		&i.NotifyJobs,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderIdentity = `-- name: GetUserByProviderIdentity :one
SELECT
    u.id,
    u.email,
    u.username,
    u.full_name,
    u.avatar_url,
    u.phone,
    u.user_location,
    u.website_url,
    u.linkedin_url,
    u.github_url,
    u.headline,
    u.user_summary,
    u.availability,
    u.min_salary,
    u.max_salary,
    u.salary_currency,
    u.years_of_experience,
    u.preferred_job_types,
    u.preferred_industries,
    u.company_stage_preference,
    u.notify_jobs,
    u.is_admin,
    u.created_at,
    u.updated_at
FROM users AS u
INNER JOIN user_accounts AS ua ON u.id = ua.user_id
WHERE ua.auth_provider = $1 AND ua.auth_provider_id = $2
`

type GetUserByProviderIdentityParams struct {
	AuthProvider   string `json:"auth_provider"`
	AuthProviderID string `json:"auth_provider_id"`
}

func (q *Queries) GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderIdentity, arg.AuthProvider, arg.AuthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.UserLocation,
		&i.WebsiteUrl,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.Headline,
		&i.UserSummary,
		&i.Availability,
		&i.MinSalary,
		&i.MaxSalary,
		&i.SalaryCurrency,
		&i.YearsOfExperience,
		&i.PreferredJobTypes,
		&i.PreferredIndustries,
		&i.CompanyStagePreference,
		&i.NotifyJobs,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($2, username),
    full_name = COALESCE($3, full_name),
    phone = COALESCE($4, phone),
    user_location = COALESCE($5, user_location),
    website_url = COALESCE($6, website_url),
    linkedin_url = COALESCE($7, linkedin_url),
    github_url = COALESCE($8, github_url),
    -- Identity
    headline = COALESCE($9, headline),
    user_summary = COALESCE($10, user_summary),
    -- Career Preferences
    availability = COALESCE($11, availability),
    min_salary = COALESCE($12, min_salary),
    max_salary = COALESCE($13, max_salary),
    salary_currency = COALESCE($14, salary_currency),
    years_of_experience
    = COALESCE($15, years_of_experience),
    preferred_job_types
    = COALESCE($16, preferred_job_types),
    preferred_industries
    = COALESCE($17, preferred_industries),
    company_stage_preference
    = COALESCE($18, company_stage_preference),
    notify_jobs = COALESCE($19, notify_jobs),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, username, full_name, avatar_url, phone, user_location, website_url, linkedin_url, github_url, headline, user_summary, availability, min_salary, max_salary, salary_currency, years_of_experience, preferred_job_types, preferred_industries, company_stage_preference, notify_jobs, is_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID                     uuid.UUID `json:"id"`
	Username               string    `json:"username"`
	FullName               *string   `json:"full_name"`
	Phone                  *string   `json:"phone"`
	UserLocation           *string   `json:"user_location"`
	WebsiteUrl             *string   `json:"website_url"`
	LinkedinUrl            *string   `json:"linkedin_url"`
	GithubUrl              *string   `json:"github_url"`
	Headline               *string   `json:"headline"`
	UserSummary            *string   `json:"user_summary"`
	Availability           *string   `json:"availability"`
	MinSalary              *int32    `json:"min_salary"`
	MaxSalary              *int32    `json:"max_salary"`
	SalaryCurrency         *string   `json:"salary_currency"`
	YearsOfExperience      *int32    `json:"years_of_experience"`
	PreferredJobTypes      []string  `json:"preferred_job_types"`
	PreferredIndustries    []string  `json:"preferred_industries"`
	CompanyStagePreference []string  `json:"company_stage_preference"`
	NotifyJobs             *bool     `json:"notify_jobs"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Phone,
		arg.UserLocation,
		arg.WebsiteUrl,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.Headline,
		arg.UserSummary,
		arg.Availability,
		arg.MinSalary,
		arg.MaxSalary,
		arg.SalaryCurrency,
		arg.YearsOfExperience,
		arg.PreferredJobTypes,
		arg.PreferredIndustries,
		arg.CompanyStagePreference,
		arg.NotifyJobs,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Phone,
		&i.UserLocation,
		&i.WebsiteUrl,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.Headline,
		&i.UserSummary,
		&i.Availability,
		&i.MinSalary,
		&i.MaxSalary,
		&i.SalaryCurrency,
		&i.YearsOfExperience,
		&i.PreferredJobTypes,
		&i.PreferredIndustries,
		&i.CompanyStagePreference,
		&i.NotifyJobs,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
