// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, username, full_name, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, username, full_name, avatar_url, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email     string  `json:"email"`
	Username  *string `json:"username"`
	FullName  *string `json:"full_name"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    username,
    full_name,
    avatar_url,
    is_admin,
    created_at,
    updated_at
FROM users
WHERE id = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderIdentity = `-- name: GetUserByProviderIdentity :one
SELECT
    u.id,
    u.email,
    u.username,
    u.full_name,
    u.avatar_url,
    u.is_admin,
    u.created_at,
    u.updated_at
FROM users AS u
INNER JOIN user_accounts AS ua ON u.id = ua.user_id
WHERE ua.auth_provider = $1 AND ua.auth_provider_id = $2
ORDER BY u.id
LIMIT 1
`

type GetUserByProviderIdentityParams struct {
	AuthProvider   string `json:"auth_provider"`
	AuthProviderID string `json:"auth_provider_id"`
}

func (q *Queries) GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderIdentity, arg.AuthProvider, arg.AuthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
