services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=jobradar
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
